all:
	zip -r `basename $(CURDIR)`-`cat ../VERSION`.zip admin site media document.xml script.php ChangeLog LICENSE.txt CREDITS.txt -i "*.php" -i "*.html" -i "*.sql" -i "*.xml" -i "*.ini" -i "*.js" -i "*.css" -i "*.png"

