all:
	cd com_document;make;mv com_document-`echo VERSION`.zip ..; cd ..
	cd mod_documents_archive;make;mv mod_documents_archive-`echo VERSION`.zip ..; cd ..
	cd mod_documents_categories;make;mv mod_documents_categories-`echo VERSION`.zip ..; cd ..
	cd mod_documents_category;make;mv mod_documents_category-`echo VERSION`.zip ..; cd ..
	cd mod_documents_latest;make;mv mod_documents_latest-`echo VERSION`.zip ..; cd ..
	cd mod_documents_news;make;mv mod_documents_news-`echo VERSION`.zip ..; cd ..
	cd mod_documents_popular;make;mv mod_documents_popular-`echo VERSION`.zip ..; cd ..
	cd plg_content_documentpdf;make;mv plg_content_documentpdf-`echo VERSION`.zip ..; cd ..
	cd plg_search_document;make;mv plg_search_document-`echo VERSION`.zip ..; cd ..

