all:
	zip -r `basename $(CURDIR)`-`cat ../VERSION`.zip `basename $(CURDIR)`.php `basename $(CURDIR)`.xml helper.php index.html tmpl language ChangeLog LICENSE.txt CREDITS.txt -i "*.php" -i "*.html" -i "*.sql" -i "*.xml" -i "*.ini" -i "*.js" -i "*.css" -i "*.png"

