all:
	zip -r `basename $(CURDIR)`-`cat ../VERSION`.zip document.php document.xml index.html tmpl language ChangeLog LICENSE.txt CREDITS.txt -i "*.php" -i "*.html" -i "*.sql" -i "*.xml" -i "*.ini" -i "*.js" -i "*.css" -i "*.png"

